---
version: '2'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_network:
        ipv4_address: 192.168.10.201
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      TZ: "Europe/Berlin"
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"
      ServerIP: 192.168.10.201
    restart: unless-stopped
networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: enx001e06368302
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
          ip_range: 192.168.10.201/32
