---
version: '2.4'
services:
  traefik:
    image: traefik:v2.0
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.network=ingress
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true
      - --log.level=ERROR
    networks:
      public:
        ipv4_address: 192.168.10.210
      ingress:
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      #- './traefik.yml:/etc/traefik/traefik.yml'
    restart: unless-stopped
networks:
  public:
    external: true
  ingress:
    external: true
