---
version: '2.4'
services:
  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.network=ingress
      - --providers.docker.exposedbydefault=false
      - --serverstransport.insecureskipverify=true
      - --api.insecure=true
      - --log.level=ERROR
      - --accesslog=true
    networks:
      public:
      ingress:
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      #- './traefik.yml:/etc/traefik/traefik.yml'
    restart: unless-stopped
networks:
  public:
  ingress:
