---
version: '2.4'
services:
  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --providers.docker=true
      - --providers.docker.network=ingress
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true
      - --log.level=ERROR
    networks:
      public:
        ipv4_address: 192.168.10.210
      ingress:
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      #- './traefik.yml:/etc/traefik/traefik.yml'
    restart: unless-stopped
    labels:
      # needs to be set for global http -> https redirect, if exposedbydefault is false
      # see https://stackoverflow.com/questions/58666711/traefik-v2-404-while-routing-http-traffic-globally-to-https
      traefik.enable: true
networks:
  public:
    external: true
  ingress:
    external: true
