---
version: '2.4'
services:
  traefik:
    image: traefik:v2.0
    networks:
      public:
        ipv4_address: 192.168.10.210
      ingress:
    volumes:
      - './traefik.yml:/etc/traefik/traefik.yml'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
networks:
  public:
    external: true
  ingress:
    external: true
