---
version: '2.4'
services:
  nextcloud:
    image: linuxserver/nextcloud:${NEXTCLOUD_VERSION:-latest}
    environment:
      TZ: Europe/Berlin
    networks:
      ingress:
      backend:
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
    # sts and redirect infos from nc doc and https://github.com/nextcloud/docker/issues/1061
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.rule: Host(`${NEXTCLOUD_FQDN:-nextcloud.docker.local}`)
      traefik.http.services.nextcloud.loadbalancer.server.port: 443
      traefik.http.services.nextcloud.loadbalancer.server.scheme: https
      traefik.http.routers.nextcloud.middlewares: nextcloud,nextcloud_redirect
      traefik.http.middlewares.nextcloud.headers.stsSeconds: 155520011
      traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.nextcloud.headers.stsPreload: true
      traefik.http.middlewares.nextcloud_redirect.redirectregex.regex: /.well-known/(card|cal)dav
      traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement: /remote.php/dav/
  # Note: connection to the DB is not handled in the ls nc image, rather than in the nc setup
  db:
    image: linuxserver/mariadb:${MARIADB_VERSION:-latest}
    networks:
      backend:
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: dummy
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - db_data:/config
    restart: unless-stopped
  # TODO: container for backup (borg/matic)
volumes:
  nextcloud_config:
  nextcloud_data:
  db_data:
networks:
  ingress:
    external: true
  backend:
