---
version: '2.4'
services:
  nextcloud:
    image: linuxserver/nextcloud
    environment:
      TZ: Europe/Berlin
    networks:
      ingress:
      backend:
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.rule: Host(`nextcloud.docker.hc2-01`)
      traefik.http.services.nextcloud.loadbalancer.server.port: 443
      traefik.http.services.nextcloud.loadbalancer.server.scheme: https
  # Note: connection to the DB is not handled in the ls nc image, rather than in the nc setup
  db:
    image: linuxserver/mariadb
    networks:
      backend:
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: dummy
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - db_data:/config
    restart: unless-stopped
  # TODO: container for backup (borg/matic)
volumes:
  nextcloud_config:
  nextcloud_data:
  db_data:
networks:
  ingress:
    external: true
  backend:
