---
- hosts: all
  vars:
    docker_data_dir: /srv/dev-disk-by-label-dockerdata

  pre_tasks:
    - name: Install docker python binding
      package:
        name: python-docker
        state: present
      become: yes
      check_mode: no

  tasks:
    - name: Create public network
      docker_network:
        name: public
        driver: macvlan
        driver_options:
          parent: lan0
        # see http://jodies.de/ipcalc?host=192.168.10.1&mask1=24&mask2=28
        ipam_config:
          - subnet: 192.168.10.0/24
            gateway: 192.168.10.1
            iprange: 192.168.10.208/28
      become: yes

    - name: Create ingress network
      docker_network:
        name: ingress
      become: yes

    - name: Create pihole docker directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ docker_data_dir }}/pihole/"
      become: yes

    - name: Place dnsmasq config
      copy:
        src: "pihole/etc-dnsmasq.d"
        dest: "{{ docker_data_dir }}/pihole/"
      become: yes

    - name: Run pihole container
      docker_container:
        name: pihole
        image: "pihole/pihole:{{ pihole_version | default('latest') }}"
        state: "{{ pihole_state | default('started') }}"
        restart_policy: unless-stopped
        env:
          TZ: "Europe/Berlin"
          ServerIP: 192.168.10.209
          DNS1: "1.1.1.1"
          DNS2: "1.0.0.1"
        dns_servers:
          - 127.0.0.1
          - 1.1.1.1
        networks:
          - name: public
            ipv4_address: 192.168.10.209
        networks_cli_compatible: yes
        volumes:
          - "{{ docker_data_dir }}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
      become: yes
